# Generated by Django 5.1.6 on 2025-04-20 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_lesson', models.DateField()),
                ('time_of_lesson', models.TimeField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Практика',
                'verbose_name_plural': 'Практика',
                'ordering': ['date_of_lesson', 'time_of_lesson'],
                'unique_together': {('teacher', 'date_of_lesson', 'time_of_lesson')},
            },
        ),
    ]
